### ISSUE TITLE
Implement CloudEvent spec?

### ISSUE THREAD

**Issue by jskulavik** [radu-matei/brigade-eventgrid-gateway#2]
I think it would be great to have this repo be one of the first to implement the new [CloudEvent Specification](https://github.com/cloudevents).

Most of the attributes are already covered in the EventGrid type, but perhaps moving that out into an interface would now be in order...

**Comment by technosophos** [comment]
It is done in #3! Huge thanks to @radu-matei for making it super easy to add.

**Comment by jskulavik** [comment]
This is so awesome folks, so awesome.  Nice work @radu-matei and @technosophos

**Comment by radu-matei** [comment]
Closing this as CloudEvents support has been merged.
Documentation coming soon 😄
